language: node_js
branches:
  only:
    - master
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
deploy:
  provider: script
  script: npm install && npm run travis-deploy
  skip_cleanup: true
  on:
    branch: master
