- label: Data Science Workflow
  links:
    - label: Overview
      href: /data-science/data-science-workflows/
    - label: Get Started
      href: /data-science/data-science-workflows/docs/getting-started.md
    - label: How to Contribute
      href: /data-science/data-science-workflows/docs/how-to-contribute.md
    - label: Data Science Projects
      href: /data-science/
- label: AI for Continuous Integration
  links:
    - label: Overview
      href: /data-science/ocp-ci-analysis/
    - label: Get Started
      href: /data-science/ocp-ci-analysis/docs/get-started.md
    - label: How to Contribute
      href: /data-science/ocp-ci-analysis/docs/how-to-contribute.md
    - label: Content
      href: /data-science/ocp-ci-analysis/docs/content.md
- label: Categorical Encoding
  links:
    - label: Overview
      href: /data-science/categorical-encoding/docs/overview.md
    - label: Get Started
      href: /data-science/categorical-encoding/docs/get-started.md
    - label: How to Contribute
      href: /data-science/categorical-encoding/docs/contribute.md
    - label: Content
      href: /data-science/categorical-encoding/docs/content.md
- label: Cloud Price Analysis
  links:
    - label: Overview
      href: /data-science/cloud-price-analysis/
    - label: Get Started
      href: /data-science/cloud-price-analysis/docs/get-started.md
    - label: How to Contribute
      href: /data-science/cloud-price-analysis/docs/contribute.md
    - label: Content
      href: /data-science/cloud-price-analysis/docs/content.md
- label: Hard Drive Failure Prediction
  links:
    - label: Overview
      href: /data-science/ceph-drive-failure/
    - label: Get Started
      href: /data-science/ceph-drive-failure/docs/get-started.md
    - label: How to Contribute
      href: /data-science/ceph-drive-failure/docs/how-to-contribute.md
    - label: Content
      href: /data-science/ceph-drive-failure/docs/content.md
- label: Mailing List Analysis
  links:
    - label: Overview
      href: /data-science/mailing-list-analysis/
    - label: Get Started
      href: /data-science/mailing-list-analysis/docs/getting-started.md
    - label: How to Contribute
      href: /data-science/mailing-list-analysis/docs/contribute.md
    - label: Content
      href: /data-science/mailing-list-analysis/docs/content.md
- label: Pet Image Detection
  links:
    - label: Overview
      href: /data-science/pet-image-detection/
    - label: Get Started
      href: /data-science/pet-image-detection/docs/get-started.md
    - label: How to Contribute
      href: /data-science/pet-image-detection/docs/how-to-contribute.md
    - label: Content
      href: /data-science/pet-image-detection/docs/content.md
- label: Time series analysis for monitoring
  links:
    - label: Overview
      href: /data-science/time-series/