- label: Data Science Projects
  links:
    - label: Projects Overview
      href: /data-science/
    - label: Categorical Encoding
      href: /data-science/categorical-encoding/docs/blog/blog.md
    - label: Configuration File Analysis
      href: /data-science/configuration-files-analysis/docs/blog/configuration-file-analysis-blog.md
    - label: Hard Drive Failure Prediction
      href: /data-science/ceph-drive-failure/docs/blog/hard-drive-failure-prediction-blog.md
    - label: Data Driven Diagnosis Discovery
      href: /data-science/openshift-anomaly-detection/docs/blog/diagnosis-discovery-blog.md
- label: Data Science Workflow
  links:
    - label: Data Science Workflow Overview
      href: /data-science/data-science-workflows/
    - label: Project Template
      href: /data-science/data-science-workflows/docs/project-document-template.md
    - label: Guidelines for Reviewing Data Science Code
      href: /data-science/data-science-workflows/docs/guidelines-for-reviewing-datascience-code.md
- label: AI for Continuous Integration
  links:
    - label: AI for Continuous Integration Overview
      href: /data-science/ocp-ci-analysis/
    - label: AI/ML for CI/CD Landscape
      href: /data-science/ocp-ci-analysis/docs/aiml-cicd-market-research.md
    - label : KPI Metrics
      href: /data-science/ocp-ci-analysis/notebooks/data-sources/TestGrid/metrics/README.md
    - label : Automated Notebook Pipeline
      href: /data-science/ocp-ci-analysis/docs/automating-using-elyra.md
    - label: Failure type classification with the TestGrid
      href: /data-science/ocp-ci-analysis/notebooks/failure-type-classification/
    - label: Initial TestGrid EDA
      href: /data-science/ocp-ci-analysis/notebooks/data-sources/TestGrid/testgrid_EDA.ipynb
    - label: Indepth TestGrid EDA
      href: /data-science/ocp-ci-analysis/notebooks/data-sources/TestGrid/testgrid_indepth_EDA.ipynb
    - label: Flaky Test Detection in TestGrid
      href: /data-science/ocp-ci-analysis/notebooks/failure-type-classification/background/testgrid_flakiness_detection.ipynb
- label: Cloud Price Analysis
  links:
    - label: Cloud Price Analysis Overview
      href: /data-science/cloud-price-analysis/
    - label: Forecasting Overview
      href: /data-science/cloud-price-analysis/docs/Forecasting.md
    - label: Initial EDA for AWS data
      href: /data-science/cloud-price-analysis/notebooks/experimental/cloud-price-analysis-EDA.ipynb
    - label: In-depth EDA for AWS data
      href: /data-science/cloud-price-analysis/notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb
- label: Time series analysis for monitoring
  links:
    - label: Time series analysis for monitoring overview
      href: /data-science/time-series/
    - label: Fetching time series metrics data
      href: /data-science/time-series/notebooks/ts-1-fetching-metrics.ipynb
    - label: Manipulating and visualizing metrics data
      href: /data-science/time-series/notebooks/ts-2-visualization.ipynb
- label: Mailing List Analysis
  links:
    - label: Mailing List Analysis Overview
      href: /data-science/mailing-list-analysis/
    - label: Keyword Analysis
      href: /data-science/mailing-list-analysis/notebooks/02_analyses/contributor_analysis.ipynb
    - label: Contributor Analysis
      href: /data-science/mailing-list-analysis/notebooks/02_analyses/keyword_analysis.ipynb
- label: Pet Image Detection
  links:
    - label: Pet Image Detection Overview
      href: /data-science/pet-image-detection/
    - label: Pet Image Detection
      href: /data-science/pet-image-detection/notebooks/image-explainability.ipynb
