- label: Get Involved
  links:
    - label: Data Science Community Meetup
      href: /data-science/operate-first-data-science-community/docs/meetup-landing-page.md
    - label: Agenda
      href: /data-science/operate-first-data-science-community/docs/content.md
- label: Data Science Workflow
  links:
    - label: Overview
      href: /data-science/data-science-workflows/
    - label: Get Started
      href: /data-science/data-science-workflows/docs/getting-started.md
    - label: How to Contribute
      href: /data-science/data-science-workflows/docs/how-to-contribute.md
    - label: Data Science Projects
      href: /data-science/projectsoverview.md
- label: AI for Continuous Integration
  links:
    - label: Overview
      href: /data-science/ai4ci/
    - label: Get Started
      href: /data-science/ai4ci/docs/get-started.md
    - label: How to Contribute
      href: /data-science/ai4ci/docs/how-to-contribute.md
    - label: Content
      href: /data-science/ai4ci/docs/content.md
- label: Categorical Encoding
  links:
    - label: Overview
      href: /data-science/categorical-encoding/docs/overview.md
    - label: Get Started
      href: /data-science/categorical-encoding/docs/get-started.md
    - label: How to Contribute
      href: /data-science/categorical-encoding/docs/contribute.md
    - label: Content
      href: /data-science/categorical-encoding/docs/content.md
- label: Cloud Price Analysis
  links:
    - label: Overview
      href: /data-science/cloud-price-analysis/
    - label: Get Started
      href: /data-science/cloud-price-analysis/docs/get-started.md
    - label: How to Contribute
      href: /data-science/cloud-price-analysis/docs/contribute.md
    - label: Content
      href: /data-science/cloud-price-analysis/docs/content.md
- label: Configuration File Analysis
  links:
    - label: Overview
      href: /data-science/configuration-files-analysis/docs/overview.md
    - label: Get Started
      href: /data-science/configuration-files-analysis/docs/get-started.md
    - label: How to Contribute
      href: /data-science/configuration-files-analysis/docs/contribute.md
    - label: Content
      href: /data-science/configuration-files-analysis/docs/content.md
- label: Data Skipping using Xskipper
  links:
    - label: Overview
      href: /data-science/data-skipping/site/docs/getting-started/operatefirst-getting-started.md
    - label: Get Started
      href: /data-science/data-skipping/notebooks/python/Xskipper - Python Sample.ipynb
- label: Github Issue Labeler
  links:
    - label: Overview
      href: /data-science/github-labeler/README.md
    - label: Get Started
      href: /data-science/github-labeler/docs/get-started.md
    - label: How to Contribute
      href: /data-science/github-labeler/docs/contribute.md
    - label: Content
      href: /data-science/github-labeler/docs/content.md
- label: Hard Drive Failure Prediction
  links:
    - label: Overview
      href: /data-science/ceph-drive-failure/
    - label: Get Started
      href: /data-science/ceph-drive-failure/docs/get-started.md
    - label: How to Contribute
      href: /data-science/ceph-drive-failure/docs/how-to-contribute.md
    - label: Content
      href: /data-science/ceph-drive-failure/docs/content.md
- label: Mailing List Analysis
  links:
    - label: Overview
      href: /data-science/mailing-list-analysis/
    - label: Get Started
      href: /data-science/mailing-list-analysis/docs/getting-started.md
    - label: How to Contribute
      href: /data-science/mailing-list-analysis/docs/contribute.md
    - label: Content
      href: /data-science/mailing-list-analysis/docs/content.md
- label: OpenShift Anomaly Detection
  links:
    - label: Overview
      href: /data-science/openshift-anomaly-detection/
    - label: Get Started
      href: /data-science/openshift-anomaly-detection/docs/get-started.md
    - label: How to Contribute
      href: /data-science/openshift-anomaly-detection/docs/how-to-contribute.md
    - label: Content
      href: /data-science/openshift-anomaly-detection/docs/content.md
- label: Pet Image Detection
  links:
    - label: Overview
      href: /data-science/pet-image-detection/
    - label: Get Started
      href: /data-science/pet-image-detection/docs/get-started.md
    - label: How to Contribute
      href: /data-science/pet-image-detection/docs/how-to-contribute.md
    - label: Content
      href: /data-science/pet-image-detection/docs/content.md
- label: Time series analysis for monitoring
  links:
    - label: Overview
      href: /data-science/time-series/
    - label: Get Started
      href: /data-science/time-series/docs/get-started.md
    - label: How to Contribute
      href: /data-science/time-series/docs/contribute.md
    - label: Content
      href: /data-science/time-series/docs/content.md
