#  Ordered list of sources of NavItems for the NavBar
# - path/to/local.yaml
# - path/to/cloned/toc.yaml

- config/data-science.yaml
- config/users.yaml
- config/operations.yaml
- config/blueprints.yaml
