- label: Mass Open Cloud (MOC) users
  href: /users/support/
- label: Jupyterhub
  links:
    - label: Troubleshooting
      href: /users/sre/runbooks/jupyterhub.md
    - label: Create a Jupyterhub image and deploy it on ODH
      href: /users/data-science-workflows/docs/create_and_deploy_jh_image.md
    - label: Elyra AIDevSecOps Tutorial
      href: /users/elyra/README.md
    - label: Using Ray with Jupyter and ODH
      href: '/users/moc-ray-demo/README.md'
- label: Prometheus
  links:
    - label: How to access Prometheus
      href: /users/apps/docs/odh/prometheus/README.md
    - label: How to monitor services using Prometheus
      href: /users/apps/docs/odh/prometheus/add_service_monitoring.md
- label: Loki
  links:
    - label: How to access Loki
      href: /users/apps/docs/observatorium/loki/README.md
    - label: How to set up Loki as data source in Grafana
      href: /users/apps/docs/observatorium/loki/add_loki_grafana_datasource.md
- label: Thanos
  links:
    - label: How to access Thanos
      href: /users/apps/docs/observatorium/thanos/README.md
- label: Kafka
  links:
    - label: How to access Kafka
      href: /users/apps/docs/odh/kafka/README.md
    - label: How to add Kafka topics
      href: /users/apps/docs/odh/kafka/add_kafka_topics.md
- label: Grafana
  links:
    - label: How to access Grafana
      href: /users/apps/docs/odh/grafana/README.md
    - label: How to add Grafana dashboards
      href: /users/apps/docs/odh/grafana/add_grafana_dashboard.md
- label: Kubeflow
  links:
    - label: How to access Kubeflow Dashboard
      href: /users/apps/docs/kubeflow/kubeflow-dashboard/README.md
    - label: How to access Kubeflow Pipelines
      href: /users/apps/docs/kubeflow/kubeflow-pipelines/README.md
