- label: Operate First Support
  href: /users/support/
- label: Mass Open Cloud (MOC)
  links:
    - label: Introduction
      href: /users/support/docs/intro.md
    - label: Request Access to Clusters
      href: /users/moc_cluster_access.md
    - label: Self Provision Access
      href: /users/support/docs/onboarding_to_cluster.md
- label: General FAQ
  links:
    - label: Secret management
      href: /users/support/docs/secret_management.md
    - label: Provisioning S3 buckets
      href: /users/support/docs/claiming_object_store.md
    - label: Issuing certificates
      href: /users/apps/docs/issuing_certificates.md
- label: Jupyterhub
  links:
    - label: Troubleshooting
      href: /users/sre/runbooks/jupyterhub.md
    - label: Create a Jupyterhub image and deploy it on ODH
      href: /users/data-science-workflows/docs/create_and_deploy_jh_image.md
    - label: Elyra AIDevSecOps Tutorial
      href: /users/elyra/README.md
    - label: Using Ray with Jupyter and ODH
      href: '/users/moc-ray-demo/README.md'
- label: Pulp
  links:
    - label: Using Pulp to host or consume Python packages
      href: /users/pulp/usage.md
- label: ArgoCD
  links:
    - label: Request Access
      href: /users/argocd_access.md
    - label: Self Provision Access
      href: /users/support/docs/onboarding_to_argocd.md
    - label: Add an Application
      href: /users/argocd-apps/docs/add_application.md
    - label: Add permissions to ArgoCD Project
      href: /users/argocd-apps/docs/add_permissions_to_project.md
- label: Prometheus
  links:
    - label: How to access Prometheus
      href: /users/apps/docs/odh/prometheus/README.md
    - label: How to monitor services using Prometheus
      href: /users/apps/docs/odh/prometheus/add_service_monitoring.md
- label: Loki
  links:
    - label: How to access Loki
      href: /users/apps/docs/observatorium/loki/README.md
    - label: How to set up Loki as data source in Grafana
      href: /users/apps/docs/observatorium/loki/add_loki_grafana_datasource.md
- label: Thanos
  links:
    - label: How to access Thanos
      href: /users/apps/docs/observatorium/thanos/README.md
- label: Kafka
  links:
    - label: Troubleshooting
      href: /users/sre/runbooks/kafka.md
    - label: How to access Kafka
      href: /users/apps/docs/odh/kafka/README.md
    - label: How to add Kafka topics
      href: /users/apps/docs/odh/kafka/add_kafka_topics.md
- label: Grafana
  links:
    - label: How to access Grafana
      href: /users/apps/docs/odh/grafana/README.md
    - label: How to add Grafana dashboards
      href: /users/apps/docs/odh/grafana/add_grafana_dashboard.md
- label: Kubeflow
  links:
    - label: How to access Kubeflow Dashboard
      href: /users/apps/docs/kubeflow/kubeflow-dashboard/README.md
    - label: How to access Kubeflow Pipelines
      href: /users/apps/docs/kubeflow/kubeflow-pipelines/README.md
- label: Trino and Superset
  links:
    - label: How to interact with Trino and Superset
      href: /users/support/docs/trino_superset_user_guide.md
