apiVersion: apps/v1
kind: Deployment
metadata:
  name: operate-first-app
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: operate-first-app
  template:
    metadata:
      labels:
        deployment: operate-first-app
    spec:
      containers:
      - name: operate-first-app
        image: quay.io/cfchase/operate-first-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 300Mi
          limits:
            cpu: 500m
            memory: 1000Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 15
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 15
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
